### PR TITLE
Use broccoli-persistent-filter instead of broccoli-filter

### PR DESCRIPTION
**Pull request by alexBaizeau**
As per ember cli perf guides: 

https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md

> broccoli-filter often needs to be replaced with broccoli-persistent-filter (we hope to re-merge the two eventually)

### CODE REVIEW

**Comment by alexBaizeau** [comment]
@outaTiME do you know if you are planning on merging this?

**Comment by outaTiME** [comment]
Hi pal, 
yup ... sooon, tonight probably new version comes 👍

**Comment by outaTiME** [comment]
Release done pal !!! 

Please check if all goes right with the new version (0.12.0) ... all test cases have passed !!!

thks for PR

**Comment by alexBaizeau** [comment]
Awsome!! thank you.

**Pull request merged**
